# Caffe 2 docker-compose
---
version: "3"
services:
  caffe:
    build:
      context: ./
    command: python3 notebook.py
    env_file:
    - /home/gctoutin/twitter.env
    volumes:
    - ./app:/app
    - /home/gctoutin/demodir:/app/demodir
    container_name: caffe
